name: "type checking for typescript"
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    name: "Validating Type"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"

      - name: Install Yarn
        run: npm install -g yarn

      - run: |
          git config http.postBuffer 1048576000
          git fetch --no-tags --depth=1000 origin +refs/heads/${{ github.base_ref }}
          git fetch --no-tags --depth=1000 origin ${{ github.sha }}

      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: .yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Validate a project when using Zero-Installs
        if: ${{ steps.yarn-cache.outputs.cache-hit != 'true' }}
        run: YARN_ENABLE_IMMUTABLE_INSTALLS=false yarn

      - name: Run Test
        run: yarn type-check:ci refs/remotes/origin/${{ github.base_ref }} --jobs 8
